# Generated by Django 4.1.7 on 2023-04-23 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('agenda', models.TextField()),
                ('datentime', models.DateTimeField(auto_now_add=True)),
                ('meeting_time', models.DateTimeField()),
                ('members', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.employee')),
            ],
        ),
    ]
