# Generated by Django 4.1.7 on 2023-04-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='members',
        ),
        migrations.AddField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(to='Employee.employee'),
        ),
    ]
