# Generated by Django 4.1.7 on 2023-03-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='finishdatetime',
            field=models.DateTimeField(default='2023-03-28 01:45:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='payment',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='paymentReceived',
            field=models.FloatField(default=1.2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='projectdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
