# Generated by Django 4.1.7 on 2023-03-28 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_remove_projectmodel_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.projectcategorymodel'),
        ),
    ]
