# Generated by Django 4.1.7 on 2023-03-28 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_projectmodel_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Project.projectcategorymodel'),
            preserve_default=False,
        ),
    ]
