# Generated by Django 4.1.7 on 2023-07-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('item', models.CharField(max_length=35)),
                ('qty', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('desc', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
    ]
